01-Nov-2023 22:51:52.836 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/387Assignment2Storefront] threw exception [An exception occurred processing [/index.jsp] at line [11]

8: <title>Insert title here</title>
9: </head>
10: <body>
11: 	<% out.print(DBConnection.getConnection()); %>
12: 	<%-- <%@include file="includes/footer.jsp" %>  --%>
13: </body>
14: </html>


Stacktrace:] with root cause
	java.net.ConnectException: Connection refused: connect
		at java.base/sun.nio.ch.Net.connect0(Native Method)
		at java.base/sun.nio.ch.Net.connect(Net.java:589)
		at java.base/sun.nio.ch.Net.connect(Net.java:578)
		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
		at java.base/java.net.Socket.connect(Socket.java:751)
		at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
		at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
		at com.mysql.cj.NativeSession.connect(NativeSession.java:121)
		at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at com.connection.DBConnection.getConnection(DBConnection.java:14)
		at org.apache.jsp.index_jsp._jspService(index_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:456)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1583)
01-Nov-2023 22:58:59.641 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/387Assignment2Storefront] threw exception [An exception occurred processing [/index.jsp] at line [11]

8: <title>Insert title here</title>
9: </head>
10: <body>
11: 	<% out.print(DBConnection.getConnection()); %>
12: 	<%-- <%@include file="includes/footer.jsp" %>  --%>
13: </body>
14: </html>


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Access denied for user 'dbuser'@'localhost' to database 'storefront'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at com.connection.DBConnection.getConnection(DBConnection.java:14)
		at org.apache.jsp.index_jsp._jspService(index_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:456)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1583)
01-Nov-2023 22:59:46.088 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/387Assignment2Storefront] threw exception [An exception occurred processing [/index.jsp] at line [11]

8: <title>Insert title here</title>
9: </head>
10: <body>
11: 	<% out.print(DBConnection.getConnection()); %>
12: 	<%-- <%@include file="includes/footer.jsp" %>  --%>
13: </body>
14: </html>


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Access denied for user 'dbuser'@'localhost' to database 'storefront'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at com.connection.DBConnection.getConnection(DBConnection.java:14)
		at org.apache.jsp.index_jsp._jspService(index_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:456)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1583)
01-Nov-2023 23:03:55.353 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/387Assignment2Storefront] threw exception [An exception occurred processing [/index.jsp] at line [11]

8: <title>Insert title here</title>
9: </head>
10: <body>
11: 	<% out.print(DBConnection.getConnection()); %>
12: 	<%-- <%@include file="includes/footer.jsp" %>  --%>
13: </body>
14: </html>


Stacktrace:] with root cause
	java.sql.SQLSyntaxErrorException: Access denied for user 'dbuser'@'localhost' to database 'storefront'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
		at com.connection.DBConnection.getConnection(DBConnection.java:14)
		at org.apache.jsp.index_jsp._jspService(index_jsp.java:133)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:456)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1583)
